/********************************************************************************
** Form generated from reading UI file 'AddObject.ui'
**
** Created by: Qt User Interface Compiler version 5.10.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ADDOBJECT_H
#define UI_ADDOBJECT_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_AddObject
{
public:
    QLabel *label;
    QPushButton *pushButton_cancel;
    QPushButton *pushButton_add;
    QTabWidget *tabWidget;
    QWidget *tab_tv;
    QFrame *frame_tv;
    QLabel *label_13;
    QLineEdit *lineEdit_model;
    QLineEdit *lineEdit_producer;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLineEdit *lineEdit_screen;
    QFrame *line_4;
    QSpinBox *spinBox_volume;
    QLabel *label_18;
    QFrame *frame_signal;
    QRadioButton *radioButton_signalOff;
    QRadioButton *radioButton_signalOn;
    QFrame *frame_power;
    QRadioButton *radioButton_pwrOn;
    QRadioButton *radioButton_pwrOff;
    QLabel *label_19;
    QSpinBox *spinBox_brightness;
    QSpinBox *spinBox_rating;
    QFrame *line_5;
    QLabel *label_20;
    QSpinBox *spinBox_width;
    QFrame *frame_speakers;
    QRadioButton *radioButton_SpeakersOn;
    QRadioButton *radioButton_SpeakersOff;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QSpinBox *spinBox_height;
    QWidget *tab_projector;
    QFrame *frame_projector;
    QLineEdit *lineEdit_model_projector;
    QLineEdit *lineEdit_producer_projector;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_28;
    QFrame *line_6;
    QLabel *label_29;
    QFrame *frame_signal_projector;
    QRadioButton *radioButton_signalOff_projector;
    QRadioButton *radioButton_signalOn_projector;
    QFrame *frame_power_projector;
    QRadioButton *radioButton_pwrOn_projector;
    QRadioButton *radioButton_pwrOff_projector;
    QLabel *label_30;
    QSpinBox *spinBox_brightness_projector;
    QSpinBox *spinBox_rating_projector;
    QLabel *label_31;
    QSpinBox *spinBox_width_projector;
    QLabel *label_32;
    QLabel *label_34;
    QSpinBox *spinBox_height_projector;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QSpinBox *spinBox_lampefficency;
    QSpinBox *spinBox_zoom;
    QSpinBox *spinBox_rotation;
    QWidget *tab_smart;
    QFrame *frame_smart;
    QLabel *label_24;
    QLineEdit *lineEdit_model_smart;
    QLineEdit *lineEdit_producer_smart;
    QLabel *label_27;
    QLabel *label_33;
    QLabel *label_35;
    QLabel *label_36;
    QLineEdit *lineEdit_screen_smart;
    QFrame *line_7;
    QSpinBox *spinBox_volume_smart;
    QLabel *label_37;
    QFrame *frame_signal_smart;
    QRadioButton *radioButton_signalOff_smart;
    QRadioButton *radioButton_signalOn_smart;
    QFrame *frame_power_smart;
    QRadioButton *radioButton_pwrOn_smart;
    QRadioButton *radioButton_pwrOff_smart;
    QLabel *label_38;
    QSpinBox *spinBox_brightness_smart;
    QSpinBox *spinBox_rating_smart;
    QFrame *line_8;
    QLabel *label_39;
    QSpinBox *spinBox_width_smart;
    QFrame *frame_speakers_smart;
    QRadioButton *radioButton_SpeakersOn_smart;
    QRadioButton *radioButton_SpeakersOff_smart;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QSpinBox *spinBox_height_smart;
    QLabel *label_46;
    QDoubleSpinBox *doubleSpinBox_soft;
    QListWidget *listWidget_apps;
    QLabel *label_2;
    QPushButton *pushButton_addapp;
    QLineEdit *lineEdit_apps;
    QPushButton *pushButton_removeapp;

    void setupUi(QDialog *AddObject)
    {
        if (AddObject->objectName().isEmpty())
            AddObject->setObjectName(QStringLiteral("AddObject"));
        AddObject->resize(764, 660);
        AddObject->setWindowOpacity(1);
        label = new QLabel(AddObject);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(50, 30, 151, 20));
        QFont font;
        font.setPointSize(12);
        label->setFont(font);
        pushButton_cancel = new QPushButton(AddObject);
        pushButton_cancel->setObjectName(QStringLiteral("pushButton_cancel"));
        pushButton_cancel->setGeometry(QRect(390, 600, 111, 31));
        pushButton_add = new QPushButton(AddObject);
        pushButton_add->setObjectName(QStringLiteral("pushButton_add"));
        pushButton_add->setEnabled(true);
        pushButton_add->setGeometry(QRect(190, 600, 111, 31));
        tabWidget = new QTabWidget(AddObject);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(30, 70, 701, 501));
        tab_tv = new QWidget();
        tab_tv->setObjectName(QStringLiteral("tab_tv"));
        frame_tv = new QFrame(tab_tv);
        frame_tv->setObjectName(QStringLiteral("frame_tv"));
        frame_tv->setEnabled(true);
        frame_tv->setGeometry(QRect(160, 0, 361, 471));
        frame_tv->setFrameShape(QFrame::NoFrame);
        label_13 = new QLabel(frame_tv);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setEnabled(true);
        label_13->setGeometry(QRect(10, 220, 131, 21));
        label_13->setFont(font);
        lineEdit_model = new QLineEdit(frame_tv);
        lineEdit_model->setObjectName(QStringLiteral("lineEdit_model"));
        lineEdit_model->setEnabled(true);
        lineEdit_model->setGeometry(QRect(160, 60, 171, 20));
        lineEdit_producer = new QLineEdit(frame_tv);
        lineEdit_producer->setObjectName(QStringLiteral("lineEdit_producer"));
        lineEdit_producer->setEnabled(true);
        lineEdit_producer->setGeometry(QRect(160, 20, 171, 20));
        label_14 = new QLabel(frame_tv);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setEnabled(true);
        label_14->setGeometry(QRect(10, 280, 131, 21));
        label_14->setFont(font);
        label_15 = new QLabel(frame_tv);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setEnabled(true);
        label_15->setGeometry(QRect(10, 60, 121, 21));
        label_15->setFont(font);
        label_16 = new QLabel(frame_tv);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setEnabled(true);
        label_16->setGeometry(QRect(10, 390, 131, 21));
        label_16->setFont(font);
        label_17 = new QLabel(frame_tv);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setEnabled(true);
        label_17->setGeometry(QRect(10, 340, 131, 21));
        label_17->setFont(font);
        lineEdit_screen = new QLineEdit(frame_tv);
        lineEdit_screen->setObjectName(QStringLiteral("lineEdit_screen"));
        lineEdit_screen->setEnabled(true);
        lineEdit_screen->setGeometry(QRect(160, 220, 171, 20));
        line_4 = new QFrame(frame_tv);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setEnabled(true);
        line_4->setGeometry(QRect(10, 250, 641, 20));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        spinBox_volume = new QSpinBox(frame_tv);
        spinBox_volume->setObjectName(QStringLiteral("spinBox_volume"));
        spinBox_volume->setEnabled(false);
        spinBox_volume->setGeometry(QRect(140, 420, 81, 22));
        spinBox_volume->setMinimum(1);
        spinBox_volume->setMaximum(100);
        spinBox_volume->setSingleStep(1);
        spinBox_volume->setValue(50);
        label_18 = new QLabel(frame_tv);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setEnabled(true);
        label_18->setGeometry(QRect(10, 100, 121, 21));
        label_18->setFont(font);
        frame_signal = new QFrame(frame_tv);
        frame_signal->setObjectName(QStringLiteral("frame_signal"));
        frame_signal->setEnabled(true);
        frame_signal->setGeometry(QRect(110, 340, 211, 21));
        radioButton_signalOff = new QRadioButton(frame_signal);
        radioButton_signalOff->setObjectName(QStringLiteral("radioButton_signalOff"));
        radioButton_signalOff->setEnabled(false);
        radioButton_signalOff->setGeometry(QRect(90, 0, 82, 21));
        radioButton_signalOff->setChecked(true);
        radioButton_signalOn = new QRadioButton(frame_signal);
        radioButton_signalOn->setObjectName(QStringLiteral("radioButton_signalOn"));
        radioButton_signalOn->setEnabled(false);
        radioButton_signalOn->setGeometry(QRect(10, 0, 82, 21));
        frame_power = new QFrame(frame_tv);
        frame_power->setObjectName(QStringLiteral("frame_power"));
        frame_power->setEnabled(true);
        frame_power->setGeometry(QRect(110, 280, 211, 21));
        radioButton_pwrOn = new QRadioButton(frame_power);
        radioButton_pwrOn->setObjectName(QStringLiteral("radioButton_pwrOn"));
        radioButton_pwrOn->setEnabled(true);
        radioButton_pwrOn->setGeometry(QRect(10, 0, 82, 21));
        radioButton_pwrOff = new QRadioButton(frame_power);
        radioButton_pwrOff->setObjectName(QStringLiteral("radioButton_pwrOff"));
        radioButton_pwrOff->setEnabled(true);
        radioButton_pwrOff->setGeometry(QRect(90, 0, 82, 21));
        radioButton_pwrOff->setChecked(true);
        label_19 = new QLabel(frame_tv);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setEnabled(true);
        label_19->setGeometry(QRect(10, 310, 131, 21));
        label_19->setFont(font);
        spinBox_brightness = new QSpinBox(frame_tv);
        spinBox_brightness->setObjectName(QStringLiteral("spinBox_brightness"));
        spinBox_brightness->setEnabled(false);
        spinBox_brightness->setGeometry(QRect(140, 310, 81, 22));
        spinBox_brightness->setMinimum(1);
        spinBox_brightness->setMaximum(100);
        spinBox_brightness->setSingleStep(1);
        spinBox_brightness->setValue(100);
        spinBox_rating = new QSpinBox(frame_tv);
        spinBox_rating->setObjectName(QStringLiteral("spinBox_rating"));
        spinBox_rating->setEnabled(true);
        spinBox_rating->setGeometry(QRect(160, 100, 81, 22));
        spinBox_rating->setMinimum(1);
        spinBox_rating->setMaximum(10);
        line_5 = new QFrame(frame_tv);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setEnabled(true);
        line_5->setGeometry(QRect(10, 370, 651, 20));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        label_20 = new QLabel(frame_tv);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setEnabled(true);
        label_20->setGeometry(QRect(10, 20, 121, 21));
        label_20->setFont(font);
        spinBox_width = new QSpinBox(frame_tv);
        spinBox_width->setObjectName(QStringLiteral("spinBox_width"));
        spinBox_width->setEnabled(true);
        spinBox_width->setGeometry(QRect(160, 180, 81, 22));
        spinBox_width->setMinimum(1);
        spinBox_width->setMaximum(8000);
        spinBox_width->setSingleStep(100);
        frame_speakers = new QFrame(frame_tv);
        frame_speakers->setObjectName(QStringLiteral("frame_speakers"));
        frame_speakers->setEnabled(true);
        frame_speakers->setGeometry(QRect(120, 390, 201, 21));
        radioButton_SpeakersOn = new QRadioButton(frame_speakers);
        radioButton_SpeakersOn->setObjectName(QStringLiteral("radioButton_SpeakersOn"));
        radioButton_SpeakersOn->setEnabled(true);
        radioButton_SpeakersOn->setGeometry(QRect(0, 0, 82, 21));
        radioButton_SpeakersOn->setChecked(false);
        radioButton_SpeakersOff = new QRadioButton(frame_speakers);
        radioButton_SpeakersOff->setObjectName(QStringLiteral("radioButton_SpeakersOff"));
        radioButton_SpeakersOff->setEnabled(true);
        radioButton_SpeakersOff->setGeometry(QRect(90, 0, 82, 21));
        radioButton_SpeakersOff->setChecked(true);
        label_21 = new QLabel(frame_tv);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setEnabled(true);
        label_21->setGeometry(QRect(10, 180, 131, 21));
        label_21->setFont(font);
        label_22 = new QLabel(frame_tv);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setEnabled(true);
        label_22->setGeometry(QRect(10, 420, 131, 21));
        label_22->setFont(font);
        label_23 = new QLabel(frame_tv);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setEnabled(true);
        label_23->setGeometry(QRect(10, 140, 141, 21));
        label_23->setFont(font);
        spinBox_height = new QSpinBox(frame_tv);
        spinBox_height->setObjectName(QStringLiteral("spinBox_height"));
        spinBox_height->setEnabled(true);
        spinBox_height->setGeometry(QRect(160, 140, 81, 22));
        spinBox_height->setMinimum(1);
        spinBox_height->setMaximum(8000);
        spinBox_height->setSingleStep(100);
        tabWidget->addTab(tab_tv, QString());
        tab_projector = new QWidget();
        tab_projector->setObjectName(QStringLiteral("tab_projector"));
        frame_projector = new QFrame(tab_projector);
        frame_projector->setObjectName(QStringLiteral("frame_projector"));
        frame_projector->setEnabled(true);
        frame_projector->setGeometry(QRect(160, 0, 361, 461));
        frame_projector->setFrameShape(QFrame::NoFrame);
        lineEdit_model_projector = new QLineEdit(frame_projector);
        lineEdit_model_projector->setObjectName(QStringLiteral("lineEdit_model_projector"));
        lineEdit_model_projector->setEnabled(true);
        lineEdit_model_projector->setGeometry(QRect(160, 60, 171, 20));
        lineEdit_producer_projector = new QLineEdit(frame_projector);
        lineEdit_producer_projector->setObjectName(QStringLiteral("lineEdit_producer_projector"));
        lineEdit_producer_projector->setEnabled(true);
        lineEdit_producer_projector->setGeometry(QRect(160, 20, 171, 20));
        label_25 = new QLabel(frame_projector);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setEnabled(true);
        label_25->setGeometry(QRect(30, 370, 131, 21));
        label_25->setFont(font);
        label_26 = new QLabel(frame_projector);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setEnabled(true);
        label_26->setGeometry(QRect(10, 60, 121, 21));
        label_26->setFont(font);
        label_28 = new QLabel(frame_projector);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setEnabled(true);
        label_28->setGeometry(QRect(30, 430, 131, 21));
        label_28->setFont(font);
        line_6 = new QFrame(frame_projector);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setEnabled(true);
        line_6->setGeometry(QRect(20, 330, 321, 20));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        label_29 = new QLabel(frame_projector);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setEnabled(true);
        label_29->setGeometry(QRect(10, 100, 121, 21));
        label_29->setFont(font);
        frame_signal_projector = new QFrame(frame_projector);
        frame_signal_projector->setObjectName(QStringLiteral("frame_signal_projector"));
        frame_signal_projector->setEnabled(true);
        frame_signal_projector->setGeometry(QRect(130, 430, 211, 21));
        radioButton_signalOff_projector = new QRadioButton(frame_signal_projector);
        radioButton_signalOff_projector->setObjectName(QStringLiteral("radioButton_signalOff_projector"));
        radioButton_signalOff_projector->setEnabled(false);
        radioButton_signalOff_projector->setGeometry(QRect(90, 0, 82, 21));
        radioButton_signalOff_projector->setChecked(true);
        radioButton_signalOn_projector = new QRadioButton(frame_signal_projector);
        radioButton_signalOn_projector->setObjectName(QStringLiteral("radioButton_signalOn_projector"));
        radioButton_signalOn_projector->setEnabled(false);
        radioButton_signalOn_projector->setGeometry(QRect(10, 0, 82, 21));
        frame_power_projector = new QFrame(frame_projector);
        frame_power_projector->setObjectName(QStringLiteral("frame_power_projector"));
        frame_power_projector->setEnabled(true);
        frame_power_projector->setGeometry(QRect(130, 370, 211, 21));
        radioButton_pwrOn_projector = new QRadioButton(frame_power_projector);
        radioButton_pwrOn_projector->setObjectName(QStringLiteral("radioButton_pwrOn_projector"));
        radioButton_pwrOn_projector->setEnabled(true);
        radioButton_pwrOn_projector->setGeometry(QRect(10, 0, 82, 21));
        radioButton_pwrOff_projector = new QRadioButton(frame_power_projector);
        radioButton_pwrOff_projector->setObjectName(QStringLiteral("radioButton_pwrOff_projector"));
        radioButton_pwrOff_projector->setEnabled(true);
        radioButton_pwrOff_projector->setGeometry(QRect(90, 0, 82, 21));
        radioButton_pwrOff_projector->setChecked(true);
        label_30 = new QLabel(frame_projector);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setEnabled(true);
        label_30->setGeometry(QRect(30, 400, 131, 21));
        label_30->setFont(font);
        spinBox_brightness_projector = new QSpinBox(frame_projector);
        spinBox_brightness_projector->setObjectName(QStringLiteral("spinBox_brightness_projector"));
        spinBox_brightness_projector->setEnabled(false);
        spinBox_brightness_projector->setGeometry(QRect(160, 400, 81, 22));
        spinBox_brightness_projector->setMinimum(1);
        spinBox_brightness_projector->setMaximum(100);
        spinBox_brightness_projector->setSingleStep(1);
        spinBox_brightness_projector->setValue(100);
        spinBox_rating_projector = new QSpinBox(frame_projector);
        spinBox_rating_projector->setObjectName(QStringLiteral("spinBox_rating_projector"));
        spinBox_rating_projector->setEnabled(true);
        spinBox_rating_projector->setGeometry(QRect(160, 100, 81, 22));
        spinBox_rating_projector->setMinimum(1);
        spinBox_rating_projector->setMaximum(10);
        label_31 = new QLabel(frame_projector);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setEnabled(true);
        label_31->setGeometry(QRect(10, 20, 121, 21));
        label_31->setFont(font);
        spinBox_width_projector = new QSpinBox(frame_projector);
        spinBox_width_projector->setObjectName(QStringLiteral("spinBox_width_projector"));
        spinBox_width_projector->setEnabled(true);
        spinBox_width_projector->setGeometry(QRect(160, 180, 81, 22));
        spinBox_width_projector->setMinimum(0);
        spinBox_width_projector->setMaximum(8000);
        spinBox_width_projector->setSingleStep(100);
        spinBox_width_projector->setValue(0);
        label_32 = new QLabel(frame_projector);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setEnabled(true);
        label_32->setGeometry(QRect(10, 180, 131, 21));
        label_32->setFont(font);
        label_34 = new QLabel(frame_projector);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setEnabled(true);
        label_34->setGeometry(QRect(10, 140, 141, 21));
        label_34->setFont(font);
        spinBox_height_projector = new QSpinBox(frame_projector);
        spinBox_height_projector->setObjectName(QStringLiteral("spinBox_height_projector"));
        spinBox_height_projector->setEnabled(true);
        spinBox_height_projector->setGeometry(QRect(160, 140, 81, 22));
        spinBox_height_projector->setMinimum(0);
        spinBox_height_projector->setMaximum(8000);
        spinBox_height_projector->setSingleStep(100);
        spinBox_height_projector->setValue(0);
        label_43 = new QLabel(frame_projector);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setEnabled(true);
        label_43->setGeometry(QRect(10, 220, 141, 21));
        label_43->setFont(font);
        label_44 = new QLabel(frame_projector);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setEnabled(true);
        label_44->setGeometry(QRect(10, 260, 131, 21));
        label_44->setFont(font);
        label_45 = new QLabel(frame_projector);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setEnabled(true);
        label_45->setGeometry(QRect(10, 300, 131, 21));
        label_45->setFont(font);
        spinBox_lampefficency = new QSpinBox(frame_projector);
        spinBox_lampefficency->setObjectName(QStringLiteral("spinBox_lampefficency"));
        spinBox_lampefficency->setEnabled(true);
        spinBox_lampefficency->setGeometry(QRect(160, 220, 81, 22));
        spinBox_lampefficency->setMinimum(0);
        spinBox_lampefficency->setMaximum(100);
        spinBox_lampefficency->setSingleStep(1);
        spinBox_lampefficency->setValue(100);
        spinBox_zoom = new QSpinBox(frame_projector);
        spinBox_zoom->setObjectName(QStringLiteral("spinBox_zoom"));
        spinBox_zoom->setEnabled(true);
        spinBox_zoom->setGeometry(QRect(160, 260, 81, 22));
        spinBox_zoom->setMinimum(0);
        spinBox_zoom->setMaximum(100);
        spinBox_zoom->setSingleStep(1);
        spinBox_zoom->setValue(1);
        spinBox_rotation = new QSpinBox(frame_projector);
        spinBox_rotation->setObjectName(QStringLiteral("spinBox_rotation"));
        spinBox_rotation->setEnabled(true);
        spinBox_rotation->setGeometry(QRect(160, 300, 81, 22));
        spinBox_rotation->setMinimum(0);
        spinBox_rotation->setMaximum(360);
        spinBox_rotation->setSingleStep(1);
        spinBox_rotation->setValue(0);
        tabWidget->addTab(tab_projector, QString());
        tab_smart = new QWidget();
        tab_smart->setObjectName(QStringLiteral("tab_smart"));
        frame_smart = new QFrame(tab_smart);
        frame_smart->setObjectName(QStringLiteral("frame_smart"));
        frame_smart->setEnabled(true);
        frame_smart->setGeometry(QRect(0, 0, 681, 471));
        frame_smart->setFrameShape(QFrame::NoFrame);
        label_24 = new QLabel(frame_smart);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setEnabled(true);
        label_24->setGeometry(QRect(10, 220, 131, 21));
        label_24->setFont(font);
        lineEdit_model_smart = new QLineEdit(frame_smart);
        lineEdit_model_smart->setObjectName(QStringLiteral("lineEdit_model_smart"));
        lineEdit_model_smart->setEnabled(true);
        lineEdit_model_smart->setGeometry(QRect(160, 60, 171, 20));
        lineEdit_producer_smart = new QLineEdit(frame_smart);
        lineEdit_producer_smart->setObjectName(QStringLiteral("lineEdit_producer_smart"));
        lineEdit_producer_smart->setEnabled(true);
        lineEdit_producer_smart->setGeometry(QRect(160, 20, 171, 20));
        label_27 = new QLabel(frame_smart);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setEnabled(true);
        label_27->setGeometry(QRect(10, 280, 131, 21));
        label_27->setFont(font);
        label_33 = new QLabel(frame_smart);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setEnabled(true);
        label_33->setGeometry(QRect(10, 60, 121, 21));
        label_33->setFont(font);
        label_35 = new QLabel(frame_smart);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setEnabled(true);
        label_35->setGeometry(QRect(10, 390, 131, 21));
        label_35->setFont(font);
        label_36 = new QLabel(frame_smart);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setEnabled(true);
        label_36->setGeometry(QRect(10, 340, 131, 21));
        label_36->setFont(font);
        lineEdit_screen_smart = new QLineEdit(frame_smart);
        lineEdit_screen_smart->setObjectName(QStringLiteral("lineEdit_screen_smart"));
        lineEdit_screen_smart->setEnabled(true);
        lineEdit_screen_smart->setGeometry(QRect(160, 220, 171, 20));
        line_7 = new QFrame(frame_smart);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setEnabled(true);
        line_7->setGeometry(QRect(10, 250, 351, 20));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        spinBox_volume_smart = new QSpinBox(frame_smart);
        spinBox_volume_smart->setObjectName(QStringLiteral("spinBox_volume_smart"));
        spinBox_volume_smart->setEnabled(false);
        spinBox_volume_smart->setGeometry(QRect(140, 420, 81, 22));
        spinBox_volume_smart->setMinimum(1);
        spinBox_volume_smart->setMaximum(100);
        spinBox_volume_smart->setSingleStep(1);
        spinBox_volume_smart->setValue(50);
        label_37 = new QLabel(frame_smart);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setEnabled(true);
        label_37->setGeometry(QRect(10, 100, 121, 21));
        label_37->setFont(font);
        frame_signal_smart = new QFrame(frame_smart);
        frame_signal_smart->setObjectName(QStringLiteral("frame_signal_smart"));
        frame_signal_smart->setEnabled(true);
        frame_signal_smart->setGeometry(QRect(110, 340, 211, 21));
        radioButton_signalOff_smart = new QRadioButton(frame_signal_smart);
        radioButton_signalOff_smart->setObjectName(QStringLiteral("radioButton_signalOff_smart"));
        radioButton_signalOff_smart->setEnabled(false);
        radioButton_signalOff_smart->setGeometry(QRect(90, 0, 82, 21));
        radioButton_signalOff_smart->setChecked(true);
        radioButton_signalOn_smart = new QRadioButton(frame_signal_smart);
        radioButton_signalOn_smart->setObjectName(QStringLiteral("radioButton_signalOn_smart"));
        radioButton_signalOn_smart->setEnabled(false);
        radioButton_signalOn_smart->setGeometry(QRect(10, 0, 82, 21));
        frame_power_smart = new QFrame(frame_smart);
        frame_power_smart->setObjectName(QStringLiteral("frame_power_smart"));
        frame_power_smart->setEnabled(true);
        frame_power_smart->setGeometry(QRect(110, 280, 211, 21));
        radioButton_pwrOn_smart = new QRadioButton(frame_power_smart);
        radioButton_pwrOn_smart->setObjectName(QStringLiteral("radioButton_pwrOn_smart"));
        radioButton_pwrOn_smart->setEnabled(true);
        radioButton_pwrOn_smart->setGeometry(QRect(10, 0, 82, 21));
        radioButton_pwrOff_smart = new QRadioButton(frame_power_smart);
        radioButton_pwrOff_smart->setObjectName(QStringLiteral("radioButton_pwrOff_smart"));
        radioButton_pwrOff_smart->setEnabled(true);
        radioButton_pwrOff_smart->setGeometry(QRect(90, 0, 82, 21));
        radioButton_pwrOff_smart->setChecked(true);
        label_38 = new QLabel(frame_smart);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setEnabled(true);
        label_38->setGeometry(QRect(10, 310, 131, 21));
        label_38->setFont(font);
        spinBox_brightness_smart = new QSpinBox(frame_smart);
        spinBox_brightness_smart->setObjectName(QStringLiteral("spinBox_brightness_smart"));
        spinBox_brightness_smart->setEnabled(false);
        spinBox_brightness_smart->setGeometry(QRect(140, 310, 81, 22));
        spinBox_brightness_smart->setMinimum(1);
        spinBox_brightness_smart->setMaximum(100);
        spinBox_brightness_smart->setSingleStep(1);
        spinBox_brightness_smart->setValue(100);
        spinBox_rating_smart = new QSpinBox(frame_smart);
        spinBox_rating_smart->setObjectName(QStringLiteral("spinBox_rating_smart"));
        spinBox_rating_smart->setEnabled(true);
        spinBox_rating_smart->setGeometry(QRect(160, 100, 81, 22));
        spinBox_rating_smart->setMinimum(1);
        spinBox_rating_smart->setMaximum(10);
        line_8 = new QFrame(frame_smart);
        line_8->setObjectName(QStringLiteral("line_8"));
        line_8->setEnabled(true);
        line_8->setGeometry(QRect(10, 370, 361, 20));
        line_8->setFrameShape(QFrame::HLine);
        line_8->setFrameShadow(QFrame::Sunken);
        label_39 = new QLabel(frame_smart);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setEnabled(true);
        label_39->setGeometry(QRect(10, 20, 121, 21));
        label_39->setFont(font);
        spinBox_width_smart = new QSpinBox(frame_smart);
        spinBox_width_smart->setObjectName(QStringLiteral("spinBox_width_smart"));
        spinBox_width_smart->setEnabled(true);
        spinBox_width_smart->setGeometry(QRect(160, 180, 81, 22));
        spinBox_width_smart->setMinimum(1);
        spinBox_width_smart->setMaximum(8000);
        spinBox_width_smart->setSingleStep(100);
        frame_speakers_smart = new QFrame(frame_smart);
        frame_speakers_smart->setObjectName(QStringLiteral("frame_speakers_smart"));
        frame_speakers_smart->setEnabled(true);
        frame_speakers_smart->setGeometry(QRect(120, 390, 201, 21));
        radioButton_SpeakersOn_smart = new QRadioButton(frame_speakers_smart);
        radioButton_SpeakersOn_smart->setObjectName(QStringLiteral("radioButton_SpeakersOn_smart"));
        radioButton_SpeakersOn_smart->setEnabled(true);
        radioButton_SpeakersOn_smart->setGeometry(QRect(0, 0, 82, 21));
        radioButton_SpeakersOn_smart->setChecked(false);
        radioButton_SpeakersOff_smart = new QRadioButton(frame_speakers_smart);
        radioButton_SpeakersOff_smart->setObjectName(QStringLiteral("radioButton_SpeakersOff_smart"));
        radioButton_SpeakersOff_smart->setEnabled(true);
        radioButton_SpeakersOff_smart->setGeometry(QRect(90, 0, 82, 21));
        radioButton_SpeakersOff_smart->setChecked(true);
        label_40 = new QLabel(frame_smart);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setEnabled(true);
        label_40->setGeometry(QRect(10, 180, 131, 21));
        label_40->setFont(font);
        label_41 = new QLabel(frame_smart);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setEnabled(true);
        label_41->setGeometry(QRect(10, 420, 131, 21));
        label_41->setFont(font);
        label_42 = new QLabel(frame_smart);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setEnabled(true);
        label_42->setGeometry(QRect(10, 140, 141, 21));
        label_42->setFont(font);
        spinBox_height_smart = new QSpinBox(frame_smart);
        spinBox_height_smart->setObjectName(QStringLiteral("spinBox_height_smart"));
        spinBox_height_smart->setEnabled(true);
        spinBox_height_smart->setGeometry(QRect(160, 140, 81, 22));
        spinBox_height_smart->setMinimum(1);
        spinBox_height_smart->setMaximum(8000);
        spinBox_height_smart->setSingleStep(100);
        label_46 = new QLabel(frame_smart);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setEnabled(true);
        label_46->setGeometry(QRect(380, 20, 121, 21));
        label_46->setFont(font);
        doubleSpinBox_soft = new QDoubleSpinBox(frame_smart);
        doubleSpinBox_soft->setObjectName(QStringLiteral("doubleSpinBox_soft"));
        doubleSpinBox_soft->setGeometry(QRect(490, 20, 91, 22));
        doubleSpinBox_soft->setSingleStep(0.01);
        doubleSpinBox_soft->setValue(1);
        listWidget_apps = new QListWidget(frame_smart);
        listWidget_apps->setObjectName(QStringLiteral("listWidget_apps"));
        listWidget_apps->setGeometry(QRect(420, 160, 201, 281));
        label_2 = new QLabel(frame_smart);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(380, 80, 91, 31));
        label_2->setFont(font);
        pushButton_addapp = new QPushButton(frame_smart);
        pushButton_addapp->setObjectName(QStringLiteral("pushButton_addapp"));
        pushButton_addapp->setEnabled(true);
        pushButton_addapp->setGeometry(QRect(570, 120, 21, 21));
        pushButton_addapp->setStyleSheet(QStringLiteral(""));
        QIcon icon;
        icon.addFile(QStringLiteral("Resources/plus.ico"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_addapp->setIcon(icon);
        lineEdit_apps = new QLineEdit(frame_smart);
        lineEdit_apps->setObjectName(QStringLiteral("lineEdit_apps"));
        lineEdit_apps->setGeometry(QRect(382, 120, 171, 20));
        pushButton_removeapp = new QPushButton(frame_smart);
        pushButton_removeapp->setObjectName(QStringLiteral("pushButton_removeapp"));
        pushButton_removeapp->setEnabled(false);
        pushButton_removeapp->setGeometry(QRect(600, 120, 21, 21));
        pushButton_removeapp->setStyleSheet(QStringLiteral(""));
        QIcon icon1;
        icon1.addFile(QStringLiteral("Resources/minus.ico"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_removeapp->setIcon(icon1);
        tabWidget->addTab(tab_smart, QString());

        retranslateUi(AddObject);
        QObject::connect(pushButton_cancel, SIGNAL(clicked()), AddObject, SLOT(close()));
        QObject::connect(radioButton_pwrOn, SIGNAL(toggled(bool)), spinBox_brightness, SLOT(setEnabled(bool)));
        QObject::connect(radioButton_pwrOn, SIGNAL(toggled(bool)), radioButton_signalOn, SLOT(setEnabled(bool)));
        QObject::connect(radioButton_pwrOn, SIGNAL(toggled(bool)), radioButton_signalOff, SLOT(setEnabled(bool)));
        QObject::connect(radioButton_SpeakersOn, SIGNAL(toggled(bool)), spinBox_volume, SLOT(setEnabled(bool)));
        QObject::connect(radioButton_pwrOn_projector, SIGNAL(toggled(bool)), radioButton_signalOff_projector, SLOT(setEnabled(bool)));
        QObject::connect(radioButton_pwrOn_projector, SIGNAL(toggled(bool)), radioButton_signalOn_projector, SLOT(setEnabled(bool)));
        QObject::connect(radioButton_pwrOn_projector, SIGNAL(toggled(bool)), spinBox_brightness_projector, SLOT(setEnabled(bool)));
        QObject::connect(radioButton_pwrOn_smart, SIGNAL(toggled(bool)), radioButton_signalOff_smart, SLOT(setEnabled(bool)));
        QObject::connect(radioButton_pwrOn_smart, SIGNAL(toggled(bool)), spinBox_brightness_smart, SLOT(setEnabled(bool)));
        QObject::connect(radioButton_SpeakersOn_smart, SIGNAL(toggled(bool)), spinBox_volume_smart, SLOT(setEnabled(bool)));
        QObject::connect(radioButton_pwrOn_smart, SIGNAL(toggled(bool)), radioButton_signalOn_smart, SLOT(setEnabled(bool)));
        QObject::connect(lineEdit_model, SIGNAL(textChanged(QString)), AddObject, SLOT(checkText()));
        QObject::connect(lineEdit_screen, SIGNAL(textChanged(QString)), AddObject, SLOT(checkText()));
        QObject::connect(lineEdit_producer, SIGNAL(textChanged(QString)), AddObject, SLOT(checkText()));
        QObject::connect(tabWidget, SIGNAL(currentChanged(int)), AddObject, SLOT(checkText()));
        QObject::connect(lineEdit_model_projector, SIGNAL(textChanged(QString)), AddObject, SLOT(checkText()));
        QObject::connect(lineEdit_producer_projector, SIGNAL(textChanged(QString)), AddObject, SLOT(checkText()));
        QObject::connect(lineEdit_producer_smart, SIGNAL(textChanged(QString)), AddObject, SLOT(checkText()));
        QObject::connect(lineEdit_screen_smart, SIGNAL(textChanged(QString)), AddObject, SLOT(checkText()));
        QObject::connect(lineEdit_model_smart, SIGNAL(textChanged(QString)), AddObject, SLOT(checkText()));
        QObject::connect(lineEdit_apps, SIGNAL(textChanged(QString)), AddObject, SLOT(checkAppInput()));
        QObject::connect(pushButton_addapp, SIGNAL(clicked()), AddObject, SLOT(onAddApp()));
        QObject::connect(pushButton_removeapp, SIGNAL(clicked()), AddObject, SLOT(onRemoveApp()));
        QObject::connect(listWidget_apps, SIGNAL(itemClicked(QListWidgetItem*)), AddObject, SLOT(appSelected()));
        QObject::connect(pushButton_add, SIGNAL(clicked()), AddObject, SLOT(submitForm()));

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(AddObject);
    } // setupUi

    void retranslateUi(QDialog *AddObject)
    {
        AddObject->setWindowTitle(QApplication::translate("AddObject", "AddObject", nullptr));
        label->setText(QApplication::translate("AddObject", "Wybierz typ obiektu :", nullptr));
        pushButton_cancel->setText(QApplication::translate("AddObject", "Anuluj", nullptr));
        pushButton_add->setText(QApplication::translate("AddObject", "Dodaj", nullptr));
        label_13->setText(QApplication::translate("AddObject", "Typ ekranu: ", nullptr));
        lineEdit_model->setText(QApplication::translate("AddObject", "domyslny", nullptr));
        lineEdit_producer->setText(QApplication::translate("AddObject", "domyslny", nullptr));
        label_14->setText(QApplication::translate("AddObject", "Zasilanie :", nullptr));
        label_15->setText(QApplication::translate("AddObject", "Model:", nullptr));
        label_16->setText(QApplication::translate("AddObject", "Glosniki :", nullptr));
        label_17->setText(QApplication::translate("AddObject", "Sygnal:", nullptr));
        lineEdit_screen->setText(QApplication::translate("AddObject", "domyslny", nullptr));
        label_18->setText(QApplication::translate("AddObject", "Ocena:", nullptr));
        radioButton_signalOff->setText(QApplication::translate("AddObject", "Wylaczony", nullptr));
        radioButton_signalOn->setText(QApplication::translate("AddObject", "Wlaczony", nullptr));
        radioButton_pwrOn->setText(QApplication::translate("AddObject", "Wlaczone", nullptr));
        radioButton_pwrOff->setText(QApplication::translate("AddObject", "Wylaczone", nullptr));
        label_19->setText(QApplication::translate("AddObject", "Jasnosc ekranu:", nullptr));
        label_20->setText(QApplication::translate("AddObject", "Producent:", nullptr));
        radioButton_SpeakersOn->setText(QApplication::translate("AddObject", "Podpiete", nullptr));
        radioButton_SpeakersOff->setText(QApplication::translate("AddObject", "Odpiete", nullptr));
        label_21->setText(QApplication::translate("AddObject", "Szerokosc ekranu:", nullptr));
        label_22->setText(QApplication::translate("AddObject", "Glosnosc:", nullptr));
        label_23->setText(QApplication::translate("AddObject", "Wysokosc ekranu:", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_tv), QApplication::translate("AddObject", "Telewizor", nullptr));
        lineEdit_model_projector->setText(QApplication::translate("AddObject", "domyslny", nullptr));
        lineEdit_producer_projector->setText(QApplication::translate("AddObject", "domyslny", nullptr));
        label_25->setText(QApplication::translate("AddObject", "Zasilanie :", nullptr));
        label_26->setText(QApplication::translate("AddObject", "Model:", nullptr));
        label_28->setText(QApplication::translate("AddObject", "Sygnal:", nullptr));
        label_29->setText(QApplication::translate("AddObject", "Ocena:", nullptr));
        radioButton_signalOff_projector->setText(QApplication::translate("AddObject", "Wylaczony", nullptr));
        radioButton_signalOn_projector->setText(QApplication::translate("AddObject", "Wlaczony", nullptr));
        radioButton_pwrOn_projector->setText(QApplication::translate("AddObject", "Wlaczone", nullptr));
        radioButton_pwrOff_projector->setText(QApplication::translate("AddObject", "Wylaczone", nullptr));
        label_30->setText(QApplication::translate("AddObject", "Jasnosc ekranu:", nullptr));
        label_31->setText(QApplication::translate("AddObject", "Producent:", nullptr));
        label_32->setText(QApplication::translate("AddObject", "Szerokosc ekranu:", nullptr));
        label_34->setText(QApplication::translate("AddObject", "Wysokosc ekranu:", nullptr));
        label_43->setText(QApplication::translate("AddObject", "Wydajnosc lampy:", nullptr));
        label_44->setText(QApplication::translate("AddObject", "Zoom:", nullptr));
        label_45->setText(QApplication::translate("AddObject", "Rotacja ekranu:", nullptr));
        spinBox_lampefficency->setSuffix(QApplication::translate("AddObject", "%", nullptr));
        spinBox_zoom->setPrefix(QApplication::translate("AddObject", "x", nullptr));
        spinBox_rotation->setSuffix(QApplication::translate("AddObject", "\302\260", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_projector), QApplication::translate("AddObject", "Projektor", nullptr));
        label_24->setText(QApplication::translate("AddObject", "Typ ekranu: ", nullptr));
        lineEdit_model_smart->setText(QApplication::translate("AddObject", "domyslny", nullptr));
        lineEdit_producer_smart->setText(QApplication::translate("AddObject", "domyslny", nullptr));
        label_27->setText(QApplication::translate("AddObject", "Zasilanie :", nullptr));
        label_33->setText(QApplication::translate("AddObject", "Model:", nullptr));
        label_35->setText(QApplication::translate("AddObject", "Glosniki :", nullptr));
        label_36->setText(QApplication::translate("AddObject", "Sygnal:", nullptr));
        lineEdit_screen_smart->setText(QApplication::translate("AddObject", "domyslny", nullptr));
        label_37->setText(QApplication::translate("AddObject", "Ocena:", nullptr));
        radioButton_signalOff_smart->setText(QApplication::translate("AddObject", "Wylaczony", nullptr));
        radioButton_signalOn_smart->setText(QApplication::translate("AddObject", "Wlaczony", nullptr));
        radioButton_pwrOn_smart->setText(QApplication::translate("AddObject", "Wlaczone", nullptr));
        radioButton_pwrOff_smart->setText(QApplication::translate("AddObject", "Wylaczone", nullptr));
        label_38->setText(QApplication::translate("AddObject", "Jasnosc ekranu:", nullptr));
        label_39->setText(QApplication::translate("AddObject", "Producent:", nullptr));
        radioButton_SpeakersOn_smart->setText(QApplication::translate("AddObject", "Podpiete", nullptr));
        radioButton_SpeakersOff_smart->setText(QApplication::translate("AddObject", "Odpiete", nullptr));
        label_40->setText(QApplication::translate("AddObject", "Szerokosc ekranu:", nullptr));
        label_41->setText(QApplication::translate("AddObject", "Glosnosc:", nullptr));
        label_42->setText(QApplication::translate("AddObject", "Wysokosc ekranu:", nullptr));
        label_46->setText(QApplication::translate("AddObject", "Wersja softu:", nullptr));
        label_2->setText(QApplication::translate("AddObject", "Aplikacje :", nullptr));
        pushButton_addapp->setText(QString());
        lineEdit_apps->setText(QApplication::translate("AddObject", "Domyslna aplikacja", nullptr));
        pushButton_removeapp->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_smart), QApplication::translate("AddObject", "SmartTV", nullptr));
    } // retranslateUi

};

namespace Ui {
    class AddObject: public Ui_AddObject {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ADDOBJECT_H
